finesources_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('listings.urls'), namespace='listings'),
    path('', include('listings.urls', namespace='listings')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from .views import *


app_name='listings'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>', product_list, name='product_list_by_category')
]

listings/models.py
from email.mime import image
from tabnanny import verbose
from unicodedata import category
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100, unique=True)
    slug=models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering=('-name',)
        verbose_name_plural='Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'listings:product_list_by_category',
            args=[self.slug]
        )

class Product(models.Model):
    category=models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name=models.CharField(max_length=100, unique=True)
    slug=models.SlugField(max_length=100, unique=True)
    image=models.ImageField(upload_to='products/')
    description=models.TextField()
    shu=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    available=models.BooleanField(default=True)

    class Meta:
        ordering=('shu',)
        verbose_name_plural='Products'

    def __str__(self):
        return self.name
        

listings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

def product_list(request, category_slug=None):
    categories=Category.objects.all()
    request_category=None
    products=Product.objects.all()

    if category_slug:
        request_category=get_object_or_404(Category,slug=category_slug)
        products=Product.objects.filter(category=request_category)

    return render(
        request,
        'product/list.html',
        {
            'categories':categories,
            'products':products
        }
    )

listings/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dar bg-danger fixed-top py-1" id="main">
        <div class="container">
            <a href="{% url 'listings:product_list' %}">
                <h3 class="font-weight-bold">Finesources</h3>

            </a>
        </div>

    </nav>
<div class="container py-5">
    {% block content %}
    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    
</body>
</html>

listings/templates/product/list.html
{% extends 'base.html' %}

{% block title %}finesauces{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-3">
    <div class="card shadow-custom border-0">
      <h4 class="p-3 font-weight-bold text-grey">
        Categories
      </h4>
      <ul class="list-group border-0 categories_list">
        <li
          {% if not requested_category %}
            class="list-group-item border-0 p-0 selected"
          {% else %}
            class="list-group-item border-0 p-0 unselected"
          {% endif %}>
            <a href="{% url 'listings:product_list' %}" 
              class="btn btn-block text-left">All</a>
        </li>      
        {% for category in categories %}
          <li
            {% if category.slug == requested_category.slug %}
              class="list-group-item border-0 p-0 selected"
            {% else %}
              class="list-group-item border-0 p-0 unselected"
            {% endif %}>
              <a href="{{ category.get_absolute_url }}" 
                class="btn btn-block text-left">
                {{ category.name }}
              </a>
          </li>
        {% endfor %}      
      </ul>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card shadow-custom border-0 mb-4">
      <div class="card-body text-center">
        <h2 class="font-weight-bold text-grey">
          {% if requested_category %}
            {{ requested_category.name }}
          {% else %}
              Our products
          {% endif %}
        </h2>        
        <div class="bottom_line"></div>
      </div>
    </div>
    <div class="row no-gutters">
    {% for product in products %}
      <div class="col-sm-6">
        <div class="card product">
          <div class="item">
            <div class="item-image">
              <img src="{{ product.image.url }}" alt="" 
                class="img-fluid rounded-0">
            </div>
            <div class="item-text">
              <div class="item-text-wrap">
                <a href="{{ product.get_absolute_url }}" 
                  class="h2 text-white text-decoration-none">
                  <i class="fas fa-search-plus"></i>
                </a> 
              </div>
            </div>
            <div class="card-body text-center">
              {{ product.name }}
              <hr>
              <span>${{ product.price }}</span>
              <div>
                <i class="fas fa-fire"></i> {{ product.shu }} SHU
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
  <div class="col-lg-3"></div>
</div>
<hr>
{% endblock content %}